import Foundation

enum CompetitiveFactVault {
    
    static let facts: [String] = [
        "The IAPLC (International Aquatic Plants Layout Contest) began in 2001 with 89 entries from Japan. By 2019 it received over 2,700 entries from 73 countries — making it the largest aquascaping competition in the world.",
        "Takashi Amano began studying Zen Buddhist aesthetics and wabi-sabi philosophy specifically to develop the Nature Aquarium style. His aquascapes are deliberately imperfect — he believed a flawless aquascape was less natural, and therefore less beautiful, than one with subtle asymmetry.",
        "HC Cuba (Hemianthus callitrichoides) was discovered in a single spring in Havana Province, Cuba, in 2003 by Holger Windeløv of Tropica. It almost wasn't introduced commercially because initial cultivation attempts repeatedly failed — it was considered too demanding to be viable.",
        "ADA Aqua Soil dramatically acidifies water via cation exchange, but this effect diminishes over 6–18 months as the exchange capacity depletes. Competition aquascapers sometimes replace substrate between competition cycles rather than compensate with increasing acid buffer additions.",
        "The 2019 IAPLC Grand Prize was won by Serkan Çetinkol (Turkey) — the first non-Japanese aquascaper to take the top prize since the contest's founding. His entry used Manten stone with Eleocharis carpet in a triangle composition evoking a mountain valley at dawn.",
        "Rotala rotundifolia's famous red-pink coloration is produced by anthocyanin pigments — the same class of pigments responsible for autumn leaf color in deciduous trees. The plant produces more anthocyanin under high light and low phosphate conditions as a photoprotective stress response.",
        "The Dutch Aquarium Hobby Association (NBAT), founded in 1956, published the first formal judging criteria for planted aquariums. Their criteria — species count, plant health, color use, naturalness — directly influenced IAPLC scoring methodology 45 years later.",
        "CO₂ injection in planted tanks was pioneered in Germany in the early 1980s. Horst Kipper and Kaspar Horst of DUPLA introduced the first commercial CO₂ systems for hobbyists in 1983 — before that, heavily planted competition tanks relied solely on fish respiration for CO₂ supply.",
        "Seiryu stone (青龍石), the most popular competition Iwagumi stone, is a metamorphic limestone from Kyoto Prefecture, Japan. Its characteristic blue-grey color and white crystalline veining come from calcite inclusions in the limestone matrix, formed under low-grade regional metamorphism.",
        "The Dry Start Method (DSM) for establishing carpet plants was developed and popularized by Tom Barr around 2006. Before DSM, establishing HC Cuba reliably was considered nearly impossible for non-expert aquascapers — the method transformed the accessible difficulty level of the style.",
        "Amano shrimp (Caridina multidentata) were introduced to the hobby by Takashi Amano in the early 1990s, named after him by the scientific community. They are the most effective algae-cleaning invertebrate for planted tanks, with each adult consuming up to 2mg of algae per hour continuously.",
        "The Golden Ratio (φ ≈ 1.618) appears to be inherently preferred by human visual processing due to its prevalence in natural forms — leaf phyllotaxis, nautilus shells, hurricane spirals. Competition aquascapes that approximate this ratio in focal point placement trigger positive aesthetic responses in judges before conscious analysis occurs.",
        "Riccardia chamedryfolia (Mini Pellia), widely used for stone texturing in competition tanks, is technically a liverwort (Marchantiophyta), not a true aquatic plant — it belongs to the same division as mosses, evolutionarily preceding the development of vascular plant tissue by 450 million years.",
        "Professional aquascapers use 'tannin pretreatment' for Seiryu stone when used with ADA substrate: the limestone raises GH and KH, fighting the substrate's buffering action. Pre-soaking stones in a mild acid (diluted vinegar, pH 4–5) for 24–48 hours passivates the reactive surface calcite, reducing the buffering conflict.",
        "The NBAT Dutch competition uses a 'street color score' where judges count distinct color zones in the aquascape. The maximum theoretical score requires 7+ distinct, clearly delineated color regions — achieved by fewer than 5% of submitted entries annually.",
        "Glossostigma elatinoides, the foundational carpet plant of the Nature Aquarium style, is native to Australia and New Zealand, where it grows as a creeping herb in seasonally flooded meadows and stream margins. It was introduced to aquascaping by Amano in 1994 after discovering it in a botanical survey.",
        "CO₂ pearling — oxygen bubbles forming on plant leaves — occurs when water is supersaturated with dissolved oxygen during active photosynthesis. The photogenic quality of pearling makes it a desired feature in competition photography. CO₂ levels above 25 mg/L during the photoperiod reliably trigger pearling in healthy plants.",
        "The record for IAPLC entries submitted from a single country in a single year belongs to Brazil (2018: 412 entries), reflecting the explosive growth of planted aquarium culture in South America, particularly in São Paulo's competitive aquascape community.",
        "Eleocharis parvula (mini hairgrass) doesn't actually grow 'hair' — its needle-like leaves are true leaves (culms) with reduced blade area, an evolutionary adaptation to reduce water resistance in fast-flowing stream habitats. The 'hair' effect in competition tanks is achieved by dense planting (3–5 plants per 2cm²) and frequent trimming that keeps culm height under 4cm.",
        "ADA (Aqua Design Amano) was founded in 1985 by Takashi Amano, initially as a nature photography company. The aquarium division grew from Amano's need for photogenic tanks as backgrounds for his fish photography. The company's entry into aquascaping equipment was essentially accidental — a by-product of artistic vision, not commercial planning.",
        "The nitrogen cycle in a new planted competition tank completes faster (7–14 days) than in a fish-only tank (3–4 weeks) primarily because aquatic plants directly assimilate ammonium (NH₄⁺), the first product of organic nitrogen decomposition, competing with Nitrosomonas bacteria and reducing the cycle's ammonia peak.",
        "Bucephalandra species, endemic to fast-flowing rivers in Borneo, are rheophytic plants — adapted to grow while submerged in turbulent water. Over 160 species have been identified since the genus was botanically described, but fewer than 20 appear in the commercial trade. Many competition-use varieties remain scientifically undescribed.",
        "The first aquascaping book with systematic design principles, 'Nature Aquarium World' by Takashi Amano (1994), was initially rejected by every major Japanese publisher for being 'too niche.' It went on to sell over 1 million copies across 15 languages and is directly credited with globalizing the hobby.",
        "Phosphate (PO₄) has been falsely blamed for algae growth in planted tanks since the 1980s based on limnological research on eutrophication in outdoor lakes — a context fundamentally different from CO₂-injected, high-light planted tanks. Tom Barr's controlled EI experiments (2001–2004) definitively showed high PO₄ does not cause algae in balanced planted systems.",
        "The aquatic plant Ludwigia arcuata, prized in competition tanks for its needle-like orange-red leaves, will turn fully green within 2 weeks if CO₂ injection stops. The plant's red coloration requires both high light and elevated CO₂ simultaneously — a useful diagnostic: if Ludwigia greens up, CO₂ has dropped."
    ]
}
